-- MySQL Script generated by MySQL Workbench
-- Mon Nov 27 14:53:59 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lojagame
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lojagame
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lojagame` DEFAULT CHARACTER SET utf8 ;
USE `lojagame` ;

-- -----------------------------------------------------
-- Table `lojagame`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojagame`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(75) NOT NULL,
  `email` VARCHAR(75) NULL,
  `telefone` VARCHAR(45) NULL,
  `senha` VARCHAR(50) NOT NULL,
  `endereco` VARCHAR(100) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lojagame`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojagame`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(45) NOT NULL,
  `descricao` TEXT NULL,
  `valor_produto` DOUBLE NOT NULL,
  `quantidade_produto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lojagame`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojagame`.`compra` (
  `idcompra` INT NOT NULL AUTO_INCREMENT,
  `cliente_idcliente` INT NOT NULL,
  `produto_idproduto` INT NOT NULL,
  `valor_compra` DOUBLE NOT NULL,
  `data_compra` DATETIME NOT NULL,
  PRIMARY KEY (`idcompra`),
  INDEX `fk_compra_cliente_idx` (`cliente_idcliente` ASC),
  INDEX `fk_compra_produto1_idx` (`produto_idproduto` ASC),
  CONSTRAINT `fk_compra_cliente`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `lojagame`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `lojagame`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
